### PR TITLE
Import 7-Zip (Windows) 15.06 beta

### PR DESCRIPTION
**Pull request by mikedep333**

### CODE REVIEW

**Comment by yprokazov** [comment]
Cool, thanks.

**Comment by mikedep333** [comment]
My pleasure.

**Comment by yprokazov** [comment]
I was sure nobody cares about having 7zip sources here instead of sourceforge. Do we know each other? How did find that repo?

**Comment by mikedep333** [comment]
At work, will reply later.

**Comment by mikedep333** [comment]
Hi @yprokazov,

We do not know eachother.

Having them on GitHub makes the code easier to view and link to, if nothing else. The code isn't browseable on GitHub.

I recently met @kjn at Flock. He is the primary developer behind [lbzip2](http://lbzip2.org/) . I was curious about what bzip2 encoder/decoder 7-Zip uses. So rather than link to the .7z file and tell him to view a file within it, I searched GitHub for the best possible repo that is a mirror of the that .7z file. Several showed up, but your repo seemed to be the best, so I linked him to https://github.com/mokejs/7zip/tree/master/windows/CPP/7zip/Compress . Of course, the outdated version stood out like a sore thumb, so I submitted a PR.

BTW,  he already knew that 7-Zip has its own bzip2 implementation, and told me about his patch that has not been reviewed yet:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=639409

**Pull request merged**
